version: '3'
services:
  dt_webservice:
    container_name: "dt_webservice"
    image: nginx:latest
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
      - '443:443'
    networks:
      - app-networks
  dt_php:
    container_name: "dt_php"
    build:
      context: ./php
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
      - ./php/php.ini:/usr/local/etc/php.ini
    ports:
      - '9000:9000'
    networks:
      - app-networks
networks:
  app-networks:
    driver: bridge
